- name: ensure that we have all packages we need
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-virtualenv
    - python-dev
    - libffi-dev
    - libssl-dev
    - sshpass
